“The world is everything that is the case.” “The world is everything that is the case.” “世界就是一切发生的事情。”  
— Ludwig Wittgenstein, *Tractatus Logico-Philosophicus*, 1921 — Ludwig Wittgenstein, *Tractatus Logico-Philosophicus*, 1921 ——路德维希·维特根斯坦，《逻辑哲学论》，1921年

**The world is not made of words.The world is not made of words. 世界并非由文字构成。**

In an [earlier essay](https://drfeifei.substack.com/p/from-words-to-worlds-spatial-intelligence), we argued that spatial intelligence is AI’s next frontier and that world models are the path to it. Here, the World Labs team and I want to go one level deeper: of the many things now being built and called ‘world models,’ which functional pieces actually compose that capacity — and what is each one for?In an [earlier essay](https://drfeifei.substack.com/p/from-words-to-worlds-spatial-intelligence), we argued that spatial intelligence is AI’s next frontier and that world models are the path to it. Here, the World Labs team and I want to go one level deeper: of the many things now being built and called ‘world models,’ which functional pieces actually compose that capacity — and what is each one for?在一篇 [早期文章](https://drfeifei.substack.com/p/from-words-to-worlds-spatial-intelligence) 中，我们提出空间智能是人工智能的下一个前沿领域，而世界模型则是通往这一目标的路径。在此，我与 World Labs 团队想进一步深入探讨：在如今被打造并冠以“世界模型”之名的众多事物中，究竟哪些功能模块真正构成了这一能力——以及每个模块的作用是什么？  
  
Language models have given machines an extraordinary command of concepts, vocabulary, and reasoning, but the physical world, virtual or real, runs on a different substrate. Where language models learn the statistical structure of text, world models learn the statistical structure of space and time: how light falls on a surface, how a garden looks from an angle no camera has captured, how objects respond to force and follow the laws of physics.Language models have given machines an extraordinary command of concepts, vocabulary, and reasoning, but the physical world, virtual or real, runs on a different substrate. Where language models learn the statistical structure of text, world models learn the statistical structure of space and time: how light falls on a surface, how a garden looks from an angle no camera has captured, how objects respond to force and follow the laws of physics.语言模型让机器对概念、词汇和推理拥有了非凡的掌控能力，但无论是虚拟的还是真实的物理世界，其运行的基础却截然不同。语言模型学习的是文本的统计结构，而世界模型学习的是空间与时间的统计结构：光线如何照射在物体表面，从某个未被相机捕捉过的角度看一座花园是什么模样，物体受力后会如何反应并遵循物理定律。

That makes “world model” one of the most important and most overloaded terms in AI today. Computer vision, robotics, reinforcement learning, and generative AI each claim to be building world models, and each means something quite different. A **video model** that produces gorgeous but physically impossible flames, a **language model** improvising a playable game, and a **physics engine** that faithfully simulates combustion all go by the same name.That makes “world model” one of the most important and most overloaded terms in AI today. Computer vision, robotics, reinforcement learning, and generative AI each claim to be building world models, and each means something quite different. A **video model** that produces gorgeous but physically impossible flames, a **language model** improvising a playable game, and a **physics engine** that faithfully simulates combustion all go by the same name.这使得“世界模型”成为如今人工智能领域最重要也最被滥用的术语之一。计算机视觉、机器人学、强化学习和生成式人工智能都声称在构建世界模型，但各自所指的含义却大相径庭。能生成华丽却违背物理规律火焰的 **视频模型** 、能即兴创作可玩游戏的 **语言模型** ，以及能精准模拟燃烧过程的 **物理引擎** ，都被冠以同一个名称。

The ancient Greeks could never agree on what the world was made of, whether fire, water, or indivisible atoms, because “world” was never a single thing. It was always a stand-in for whatever totality a given thinker needed to reason about. AI has inherited the same problem, at exactly the moment when the field needs precision.The ancient Greeks could never agree on what the world was made of, whether fire, water, or indivisible atoms, because “world” was never a single thing. It was always a stand-in for whatever totality a given thinker needed to reason about. AI has inherited the same problem, at exactly the moment when the field needs precision.古希腊人永远无法就世界由什么构成达成一致——是火、水，还是不可分割的原子，因为“世界”从来都不是一个单一的事物。它始终是某个特定思想家进行推理时所需的任何整体概念的代名词。而人工智能恰恰在这个领域需要精准性的时刻，继承了同样的问题。

### The loop beneath the taxonomyThe loop beneath the taxonomy 分类法之下的循环

Cutting through that confusion starts with a diagram older than any of the technology in question. Reinforcement learning textbooks, including the canonical Sutton and Barto, have used a version of the same picture for decades to describe how an agent interacts with a world. The formal name for this picture is the partially observable Markov decision process, or POMDP, and the original definition of the term “world model” belongs to that tradition.Cutting through that confusion starts with a diagram older than any of the technology in question. Reinforcement learning textbooks, including the canonical Sutton and Barto, have used a version of the same picture for decades to describe how an agent interacts with a world. The formal name for this picture is the partially observable Markov decision process, or POMDP, and the original definition of the term “world model” belongs to that tradition.理清这一困惑，要从一张比所有相关技术都更古老的示意图说起。包括经典的《萨顿与巴托强化学习》在内的强化学习教材，数十年来一直用同一张图来描述智能体与环境的交互方式。这张图的正式名称是部分可观察马尔可夫决策过程（POMDP），而“世界模型”这一术语的最初定义，就源自这一传统。

An agent, which can be a person, a robot, or a software system, takes actions. Those actions affect the state of the world. The agent never sees the state directly. What reaches the agent are observations: the photons that fall on a retina, the readings from a sensor, and the pixels in a video frame. New observations inform new actions, and the loop continues.An agent, which can be a person, a robot, or a software system, takes actions. Those actions affect the state of the world. The agent never sees the state directly. What reaches the agent are observations: the photons that fall on a retina, the readings from a sensor, and the pixels in a video frame. New observations inform new actions, and the loop continues.一个智能体可以是人、机器人或软件系统，它会采取行动。这些行动会影响世界的状态。智能体无法直接看到这个状态。传递到智能体的是观测结果：落在视网膜上的光子、传感器的读数以及视频帧中的像素。新的观测会指导新的行动，如此循环往复。

The word “state” needs unpacking, because the meaning shifts from field to field. This is not the chemist’s state, the difference between solid, liquid, and gas. This is the physicist’s and roboticist’s state: a complete description of what is happening in the world at a given moment, including every object, every position, every velocity, every property. State is the underlying reality of the world; complete in principle, but never directly visible to any agent inside it. Observations are an agent’s partial view of that reality. Actions are what the agent does in response.The word “state” needs unpacking, because the meaning shifts from field to field. This is not the chemist’s state, the difference between solid, liquid, and gas. This is the physicist’s and roboticist’s state: a complete description of what is happening in the world at a given moment, including every object, every position, every velocity, every property. State is the underlying reality of the world; complete in principle, but never directly visible to any agent inside it. Observations are an agent’s partial view of that reality. Actions are what the agent does in response.“状态”一词需要拆解来看，因为它的含义因领域而异。这并非化学家口中的状态——即固态、液态与气态之间的区别。它指的是物理学家和机器人学专家所说的状态：在特定时刻对世界上所发生一切的完整描述，涵盖所有物体、每个位置、各项速度以及每一项属性。状态是世界背后的本质实在，理论上是完整无缺的，但对于身处其中的任何主体而言，它都无法被直接观测。观测是主体对这一实在的局部认知，而行动则是主体对此做出的回应。

This loop — agent to action to state to observation and back — is the structure that gave the modern term “world model” its technical meaning. The phrase itself is older, traced to Kenneth Craik’s 1943 proposal that minds reason by running “small-scale models” of reality, and carried into neural networks by the late 1980s and early 1990s. And the loop also explains what people mean by the term today. The different things now being called world models are in fact different projections of this same loop. Each one outputs a different piece of it.This loop — agent to action to state to observation and back — is the structure that gave the modern term “world model” its technical meaning. The phrase itself is older, traced to Kenneth Craik’s 1943 proposal that minds reason by running “small-scale models” of reality, and carried into neural networks by the late 1980s and early 1990s. And the loop also explains what people mean by the term today. The different things now being called world models are in fact different projections of this same loop. Each one outputs a different piece of it.这个循环——从智能体到行动、再到状态、观察，然后回到智能体——赋予了现代术语“世界模型”技术层面的含义。这个术语本身出现得更早，可追溯至肯尼斯·克雷尔1943年提出的观点，即人类思维通过运行现实的“小型模型”进行推理，而这一概念在20世纪80年代末90年代初被引入神经网络领域。同时，这个循环也解释了如今人们对该术语的定义。如今被称作世界模型的各类事物，实际上都是这同一循环的不同投射，每一种都输出该循环的不同部分。

### Three functions of a world modelThree functions of a world model 世界模型的三大功能

**The first kind of world model is a renderer.** **A renderer outputs observations in the form of pixels meant for human eyes, and the quality that matters most is visual fidelity.** A video model that turns a text prompt into a cinematic drone shot is a renderer. So is an interactive system like ***Google’s Genie 3***, or World Labs’ own ***RTFM***, where the model generates frames in real time conditioned on user input. The model carries no explicit understanding of three-dimensional structure. It produces what a viewer would see, not what is. The buildings in the drone shot may look flawless from above, but try to drive through the city below and they fall apart.**The first kind of world model is a renderer.** **A renderer outputs observations in the form of pixels meant for human eyes, and the quality that matters most is visual fidelity.** A video model that turns a text prompt into a cinematic drone shot is a renderer. So is an interactive system like ***Google’s Genie 3***, or World Labs’ own ***RTFM***, where the model generates frames in real time conditioned on user input. The model carries no explicit understanding of three-dimensional structure. It produces what a viewer would see, not what is. The buildings in the drone shot may look flawless from above, but try to drive through the city below and they fall apart.**第一种世界模型是渲染器。** **渲染器以像素形式输出供人眼观看的观测结果，其最关键的质量指标是视觉保真度。** 能将文本提示转化为电影级无人机镜头的视频模型就是渲染器。 ***谷歌的Genie 3*** 这类交互系统，以及World Labs自主研发的 ***RTFM*** 也属于此类，这类模型会根据用户输入实时生成画面帧。该模型对三维结构没有明确的理解，它生成的是观察者所能看到的景象，而非客观存在的事物。无人机镜头中的建筑从上方看可能完美无缺，但如果试图在下方的城市中穿行，它们就会原形毕露。

**The second kind is a simulator. A simulator outputs state: a geometrically, physically or dynamically faithful representation of the world that humans and computer programs can both compute on and interact with.** Where the renderer’s contract is purely visual, the simulator’s contract is structural, demanding geometry that holds up under inspection, physics that respects Newton’s laws, and dynamics that behave the way the world needs to behave given the laws of physics. A simulator serves two consumers at once. Human professionals such as architects, designers, filmmakers, and game developers need accuracy beyond visual plausibility. Computer programs such as reinforcement learning agents, robot controllers, and autonomous vehicles use simulators as training grounds where they can interact with the world at scale, testing scenarios that would be dangerous, expensive, or impossible to run in reality.**The second kind is a simulator. A simulator outputs state: a geometrically, physically or dynamically faithful representation of the world that humans and computer programs can both compute on and interact with.** Where the renderer’s contract is purely visual, the simulator’s contract is structural, demanding geometry that holds up under inspection, physics that respects Newton’s laws, and dynamics that behave the way the world needs to behave given the laws of physics. A simulator serves two consumers at once. Human professionals such as architects, designers, filmmakers, and game developers need accuracy beyond visual plausibility. Computer programs such as reinforcement learning agents, robot controllers, and autonomous vehicles use simulators as training grounds where they can interact with the world at scale, testing scenarios that would be dangerous, expensive, or impossible to run in reality.**第二类是模拟器。模拟器会输出一种状态：以几何、物理或动态的方式真实还原世界，人类和计算机程序既可以对其进行计算，也能与之交互。** 渲染器的核心要求仅在于视觉效果，而模拟器的核心要求则是结构层面的，它需要具备经得起检验的几何形态、遵循牛顿定律的物理规则，以及符合物理定律下世界应有的运行规律的动态特性。模拟器同时服务两类用户。建筑师、设计师、电影制作人和游戏开发者等专业人士，需要的精度远超视觉上的合理性。强化学习智能体、机器人控制器、自动驾驶汽车等计算机程序，则将模拟器当作训练场地，它们可以在其中与虚拟世界进行大规模交互，测试那些在现实中实施会有危险、成本高昂或根本无法实现的场景。

**The third kind is a planner. A planner outputs actions.** Given an observation and a goal, a planner answers the question of what the agent should do next. This is, in many ways, the inverse of the renderer. Where a renderer takes actions as input and produces observations, a planner takes observations as input and produces actions, closing the perception-action loop. Vision-Language-Action models, model-based systems, and the new wave of World Action Models are all attempts at planners: systems that can decide what a robot should do in an unstructured world.**The third kind is a planner. A planner outputs actions.** Given an observation and a goal, a planner answers the question of what the agent should do next. This is, in many ways, the inverse of the renderer. Where a renderer takes actions as input and produces observations, a planner takes observations as input and produces actions, closing the perception-action loop. Vision-Language-Action models, model-based systems, and the new wave of World Action Models are all attempts at planners: systems that can decide what a robot should do in an unstructured world.**第三种是规划器。规划器输出动作。** 给定观测值和目标，规划器会回答智能体下一步该做什么的问题。在很多方面，这与渲染器是相反的。渲染器以动作为输入并生成观测值，而规划器则以观测值为输入并生成动作，形成了感知-行动闭环。视觉-语言-动作模型、基于模型的系统以及新一代的世界动作模型，都是对规划器的探索：这些系统能够决定机器人在非结构化环境中应该执行哪些动作。

These three categories describe most of what is actually shipping today, and the distinction between them is useful in practice. The categories are not, however, fundamentally separate. The same underlying knowledge of how the world works—geometry, physics, dynamics—sits beneath all of them. A model that can render a cup from any angle ought, in principle, to be able to simulate what happens when the cup is pushed and plan a hand to pick the cup up. Increasingly, the most interesting research deliberately blurs the boundaries between the three.These three categories describe most of what is actually shipping today, and the distinction between them is useful in practice. The categories are not, however, fundamentally separate. The same underlying knowledge of how the world works—geometry, physics, dynamics—sits beneath all of them. A model that can render a cup from any angle ought, in principle, to be able to simulate what happens when the cup is pushed and plan a hand to pick the cup up. Increasingly, the most interesting research deliberately blurs the boundaries between the three.这三类涵盖了目前实际应用中绝大多数的内容，它们之间的区别在实际场景中具有实用价值。不过，这些类别并非本质上相互独立。支撑它们的都是关于世界运行规律的底层知识——几何学、物理学和动力学。从理论上讲，一个能从任意角度渲染出杯子的模型，应当能够模拟杯子被推动时发生的情况，并规划出一只手去拿起杯子的动作。如今，越来越多前沿的研究正有意模糊这三者之间的界限。

![](https://substackcdn.com/image/fetch/$s_!pWY_!,w_1456,c_limit,f_webp,q_auto:good,fl_lossy/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F0c3b76fd-e9fa-4c68-8f16-5cb4c6d86c26_1080x608.gif)

### Why simulation is the linchpinWhy simulation is the linchpin 为何仿真是关键核心

**Of the three categories, the simulator gets the least public attention, and is the most consequential of the three. This essay addresses this asymmetry.Of the three categories, the simulator gets the least public attention, and is the most consequential of the three. This essay addresses this asymmetry.在这三类中，模拟器获得的公众关注最少，但其影响却是三者中最大的。本文探讨了这种不对称现象。**

**The renderer is by far the most commercially mature**. A number of image- or text-to-video products are expanding in the consumer or enterprise markets rapidly. Google’s Nano Banana model has put renderer-quality image generation in the hands of potentially hundreds of millions of users. The technology is real, and the markets are real. Yet renderers optimize for visual plausibility rather than physical accuracy, and that ceiling matters. Their outputs are beautiful, but they cannot be trusted to design a building or train a robot.**The renderer is by far the most commercially mature**. A number of image- or text-to-video products are expanding in the consumer or enterprise markets rapidly. Google’s Nano Banana model has put renderer-quality image generation in the hands of potentially hundreds of millions of users. The technology is real, and the markets are real. Yet renderers optimize for visual plausibility rather than physical accuracy, and that ceiling matters. Their outputs are beautiful, but they cannot be trusted to design a building or train a robot.**渲染器是目前商业成熟度最高的技术** 。多款图像或文生视频产品正快速进军消费级与企业级市场。谷歌的 Nano Banana 模型让数亿潜在用户都能体验到渲染级画质的图像生成。这项技术是真实存在的，相关市场也已成型。然而渲染器优化的是视觉上的逼真度，而非物理层面的准确性，这一上限是关键。它们生成的内容虽精美，却无法用于建筑设计或机器人训练。

**The planner is the most intriguing and the most nascent,** closely connected to the rapidly evolving field of robotic learning**.** The field has produced robotic demos in the last two years that look impressive in videos, but candor is required about what those demos actually show. Almost all have been confined to heavily constrained laboratory setups, with narrow object sets and short task horizons. None have been validated at the complexity, variability, or duration that real-world deployment demands. The gap between a compelling demo reel and a robot that reliably works in a kitchen, a warehouse, or an operating room remains vast. The commercial bets are nonetheless substantial. A wave of well-funded entrants is racing to ship general-purpose planning systems, while the largest infrastructure players are positioning planning atop broader simulation stacks. A robot that can plan is a robot that can work, and the entire industry is racing to be the one that gets there first.**The planner is the most intriguing and the most nascent,** closely connected to the rapidly evolving field of robotic learning**.** The field has produced robotic demos in the last two years that look impressive in videos, but candor is required about what those demos actually show. Almost all have been confined to heavily constrained laboratory setups, with narrow object sets and short task horizons. None have been validated at the complexity, variability, or duration that real-world deployment demands. The gap between a compelling demo reel and a robot that reliably works in a kitchen, a warehouse, or an operating room remains vast. The commercial bets are nonetheless substantial. A wave of well-funded entrants is racing to ship general-purpose planning systems, while the largest infrastructure players are positioning planning atop broader simulation stacks. A robot that can plan is a robot that can work, and the entire industry is racing to be the one that gets there first.**规划器是最引人入胜且最具新生属性的技术** ，与快速发展的机器人学习领域密切相关 **。** 过去两年，该领域产出的机器人演示在视频中看起来令人印象深刻，但我们必须坦诚地看待这些演示实际展示的内容。几乎所有演示都局限于高度受限的实验室环境，仅包含有限的物体集合，且任务周期较短。没有一项演示经过了现实世界部署所要求的复杂性、多变性和时长验证。引人入胜的演示集锦与能在厨房、仓库或手术室稳定工作的机器人之间，仍存在巨大差距。尽管如此，行业的商业投入依然巨大。一批资金充裕的新入局者竞相推出通用规划系统，而大型基础设施企业也在更广泛的仿真技术栈之上布局规划功能。能够进行规划的机器人才具备工作能力，整个行业都在竞相成为率先实现这一目标的参与者。

**Simulation is the bridge between the two.** If language is an abstraction of the world and pixels are a projection of it, then geometry, physics, and dynamics are the world itself. A simulator must work at that level: the structural backbone from which both visual appearance (for renderers) and action consequences (for planners) can be derived. **Simulation is the bridge between the two.** If language is an abstraction of the world and pixels are a projection of it, then geometry, physics, and dynamics are the world itself. A simulator must work at that level: the structural backbone from which both visual appearance (for renderers) and action consequences (for planners) can be derived. **仿真是连接两者的桥梁。** 如果语言是对世界的抽象，像素是对世界的投影，那么几何、物理和动力学就是世界本身。模拟器必须在这个层面上发挥作用：它是构建视觉外观（供渲染器使用）和行为结果（供规划器使用）的结构支柱。  
  
A model that masters simulation can project its understanding into pixels for human consumption, and into action predictions for embodied agents. A model that masters only rendering, or only planning, cannot do either. The commercial surface area is enormous. NVIDIA’s Omniverse alone targets what the company estimates as more than a trillion dollars of addressable market in factories, warehouses, supply chains, and digital twins. Robotics training, autonomous vehicle testing, architectural visualization, engineering, and drug discovery all depend on something simulation-shaped.A model that masters simulation can project its understanding into pixels for human consumption, and into action predictions for embodied agents. A model that masters only rendering, or only planning, cannot do either. The commercial surface area is enormous. NVIDIA’s Omniverse alone targets what the company estimates as more than a trillion dollars of addressable market in factories, warehouses, supply chains, and digital twins. Robotics training, autonomous vehicle testing, architectural visualization, engineering, and drug discovery all depend on something simulation-shaped.掌握模拟能力的模型，能将自身的理解转化为可供人类查看的像素画面，也能转化为具身智能体的行动预测。而仅掌握渲染或仅掌握规划的模型，这两件事都做不到。其商业应用空间极为广阔。单是英伟达的 Omniverse 平台，就瞄准了该公司估算的超万亿美元可拓展市场，覆盖工厂、仓库、供应链及数字孪生领域。机器人训练、自动驾驶测试、建筑可视化、工程设计和药物研发，全都依赖于模拟相关的技术。

The hardest open problems in the field live there too. Three-dimensional data with explicit geometry, material properties, and physical annotations is orders of magnitude scarcer than the internet video that renderers train on. The sim-to-real gap, which is the difference between how things behave in simulation and how they behave in reality, persists. Generative simulators introduce a new risk on top of that: AI-generated geometry can look correct while containing self-intersections or wrong scale that produce nonsensical physics. Multi-physics simulation at scale, where rigid bodies, deformable objects, fluids, and cloth all interact, remains orders of magnitude more expensive than single-domain simulation.The hardest open problems in the field live there too. Three-dimensional data with explicit geometry, material properties, and physical annotations is orders of magnitude scarcer than the internet video that renderers train on. The sim-to-real gap, which is the difference between how things behave in simulation and how they behave in reality, persists. Generative simulators introduce a new risk on top of that: AI-generated geometry can look correct while containing self-intersections or wrong scale that produce nonsensical physics. Multi-physics simulation at scale, where rigid bodies, deformable objects, fluids, and cloth all interact, remains orders of magnitude more expensive than single-domain simulation.该领域最棘手的未解决问题也存在于此。具备明确几何结构、材料属性和物理标注的三维数据，其稀缺程度远超渲染模型所训练的互联网视频。仿真到现实的差距——即事物在仿真环境中的表现与在现实世界中的表现之间的差异——依然存在。生成式模拟器在此基础上还带来了新的风险：人工智能生成的几何结构看似正确，却可能包含自相交或比例错误的问题，从而产生无意义的物理效果。大规模多物理场仿真（其中刚体、可变形物体、流体和布料全部相互作用）的成本，仍比单领域仿真高出数个数量级。

At World Labs, ***Marble*** **is our first move into this territory.** It takes multimodal prompts (text, image, video, or spatial sketch) and generates explorable 3D environments, outputting Gaussian splats for visual exploration alongside collision meshes a physics engine can operate on. But Marble is only the first chapter of a much longer arc being written across the field as the lines between rendering, simulation, and planning begin to collapse.At World Labs, ***Marble*** **is our first move into this territory.** It takes multimodal prompts (text, image, video, or spatial sketch) and generates explorable 3D environments, outputting Gaussian splats for visual exploration alongside collision meshes a physics engine can operate on. But Marble is only the first chapter of a much longer arc being written across the field as the lines between rendering, simulation, and planning begin to collapse.在 World Labs， ***Marble*** 是我们进军这一领域的第一步。它支持多模态提示（文本、图像、视频或空间草图），并生成可探索的3D环境，输出用于视觉探索的高斯点云，以及物理引擎可操作的碰撞网格。但随着渲染、模拟和规划之间的界限开始模糊，Marble 只是我们在这一领域书写的漫长篇章中的第一章。

### Where the boundaries are collapsing and what comes nextWhere the boundaries are collapsing and what comes next边界正在何处消融，以及接下来会发生什么

But more is to come. The most important pattern in the field right now is that the three categories are starting to blend into one another. The shared insight is that the knowledge required to render a world, simulate it, and act in it is largely the same. Continuing the earlier example, a model that truly understands how a cup sits on a table (its geometry, material properties, response to force, etc.) should be able to render that cup from any angle, simulate what happens when the cup is pushed, and plan for a hand to pick the cup up. The three categories are three projections of a single underlying understanding.But more is to come. The most important pattern in the field right now is that the three categories are starting to blend into one another. The shared insight is that the knowledge required to render a world, simulate it, and act in it is largely the same. Continuing the earlier example, a model that truly understands how a cup sits on a table (its geometry, material properties, response to force, etc.) should be able to render that cup from any angle, simulate what happens when the cup is pushed, and plan for a hand to pick the cup up. The three categories are three projections of a single underlying understanding.但这还只是开始。目前该领域最重要的趋势是这三大类别开始相互融合。它们的共同核心在于：构建一个世界、模拟它并在其中行动所需的知识，本质上大体相同。延续之前的例子，一个真正理解杯子如何放置在桌面上（包括其几何形状、物理特性、受力反应等）的模型，应当能够从任意角度渲染这个杯子，模拟杯子被推动时发生的情况，并规划出用手拿起杯子的动作。这三大类别只是同一底层认知的三种不同呈现形式。

For example: a small but growing number of recent work from various robotics labs have demonstrated that—at least conceptually—a pretrained video renderer can be used as the backbone for joint world-and-action prediction, suggesting a bridge between the renderer and the planner by letting one model imagine what will happen and what to do. World Labs’ Marble already outputs Gaussian splats and collision meshes from a single model, dissolving the boundary between the renderer and the simulator. **Every level is moving from passive output to interactive system,** with renderers becoming action-conditioned, simulators generating worlds that are more controllable and editable, and planners deliberating rather than just reacting.For example: a small but growing number of recent work from various robotics labs have demonstrated that—at least conceptually—a pretrained video renderer can be used as the backbone for joint world-and-action prediction, suggesting a bridge between the renderer and the planner by letting one model imagine what will happen and what to do. World Labs’ Marble already outputs Gaussian splats and collision meshes from a single model, dissolving the boundary between the renderer and the simulator. **Every level is moving from passive output to interactive system,** with renderers becoming action-conditioned, simulators generating worlds that are more controllable and editable, and planners deliberating rather than just reacting.例如：来自各机器人实验室的近期研究虽数量不多但持续增长，已证明——至少在概念层面——预训练的视频渲染器可作为联合世界与动作预测的骨干模型，通过让单个模型设想未来发生的情况及应采取的行动，搭建起渲染器与规划器之间的桥梁。World Labs 公司的 Marble 系统已能通过单一模型输出高斯点云与碰撞网格，打破了渲染器与模拟器之间的界限。 **每个层级都在从被动输出向交互式系统演进，** 渲染器具备了动作条件反射特性，模拟器能生成更易控制和编辑的虚拟世界，规划器也从单纯的被动响应转向主动决策。

**The logical endpoint is a unified world model: one foundation model that can render photorealistic views, produce physically accurate structure, and plan action sequences, switching between output modalities depending on what the downstream consumer needs.** We will still face a number of daunting challenges. The data picture is uneven, with renderers awash in internet video while simulators and planners face acute shortages of 3D assets and robot demonstrations. Optimizing for visual beauty can sacrifice the precision a robot or a high-fidelity simulation needs. Reconciling these tensions inside a single architecture is the defining open problem in world model research today, and this is what World Labs sets out to do as we continue to evolve Marble.**The logical endpoint is a unified world model: one foundation model that can render photorealistic views, produce physically accurate structure, and plan action sequences, switching between output modalities depending on what the downstream consumer needs.** We will still face a number of daunting challenges. The data picture is uneven, with renderers awash in internet video while simulators and planners face acute shortages of 3D assets and robot demonstrations. Optimizing for visual beauty can sacrifice the precision a robot or a high-fidelity simulation needs. Reconciling these tensions inside a single architecture is the defining open problem in world model research today, and this is what World Labs sets out to do as we continue to evolve Marble.**逻辑上的终极目标是构建一个统一的世界模型：即一个基础模型，能够生成照片级逼真的视图、构建物理上精准的结构并规划动作序列，根据下游使用者的需求在不同输出模态间切换。** 我们仍将面临诸多艰巨挑战。数据分布极不均衡，渲染领域充斥着网络视频，而模拟器和规划器则严重缺乏3D资产与机器人演示数据。对视觉美观的优化可能会牺牲机器人或高保真模拟所需的精度。在单一架构内调和这些矛盾，是当下世界模型研究中最核心的待解问题，这也是世界实验室（World Labs）在持续迭代Marble模型时致力于实现的目标。

![](https://substackcdn.com/image/fetch/$s_!6p3J!,w_1456,c_limit,f_webp,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F89a1f167-5ce4-4ed5-a6b5-5511237bac79_1080x608.gif)

The direction, however, is clear. The same bet the field has been making since the late 1980s — that a sufficiently rich model of the world is all that any agent needs to see worlds, build them, and act in them — is the bet now driving an entire generation of research. What gives that “big bet” weight is the convergence already underway: three threads, each already driving and shaping multi-billion-dollar industries on its own, that began as separate research programs are starting to behave like one. Taken together, as the boundaries between them collapse, they will reshape something larger: the relationship between machine intelligence and the physical world it inhabits - the long arc of spatial intelligence.The direction, however, is clear. The same bet the field has been making since the late 1980s — that a sufficiently rich model of the world is all that any agent needs to see worlds, build them, and act in them — is the bet now driving an entire generation of research. What gives that “big bet” weight is the convergence already underway: three threads, each already driving and shaping multi-billion-dollar industries on its own, that began as separate research programs are starting to behave like one. Taken together, as the boundaries between them collapse, they will reshape something larger: the relationship between machine intelligence and the physical world it inhabits - the long arc of spatial intelligence.

Language gave machines a way to talk about that world. World models are how machines will finally come to understand, imagine, reason and interact with it.Language gave machines a way to talk about that world. World models are how machines will finally come to understand, imagine, reason and interact with it.

---

*If this mission excites you, check out our open roles on the [World Labs careers page](https://job-boards.greenhouse.io/worldlabs) If this mission excites you, check out our open roles on the [World Labs careers page](https://job-boards.greenhouse.io/worldlabs)*