## Towards a Working Definition of Designing Generative User Interfaces面向生成式用户界面设计的工作定义

Kyungho Lee Expressive Computing Lab.  
Department of Design, UNISTUlsanRepublic of Korea [kyungho@unist.ac.kr](mailto:kyungho@unist.ac.kr)

(2025)

###### Abstract. 摘要。

Generative UI is transforming interface design by facilitating AI-driven collaborative workflows between designers and computational systems. This study establishes a working definition of Generative UI through a multi-method qualitative approach, integrating insights from a systematic literature review of 127 publications, expert interviews with 18 participants, and analyses of 12 case studies. Our findings identify five core themes that position Generative UI as an iterative and co-creative process. We highlight emerging design models, including hybrid creation, curation-based workflows, and AI-assisted refinement strategies. Additionally, we examine ethical challenges, evaluation criteria, and interaction models that shape the field. By proposing a conceptual foundation, this study advances both theoretical discourse and practical implementation, guiding future HCI research toward responsible and effective generative UI design practices.  
生成式 UI 通过促进设计师与计算系统之间的 AI 驱动的协作工作流程，正在改变界面设计。本研究通过多方法定性方法建立生成式 UI 的工作定义，整合了 127 篇出版物的系统文献综述、18 位参与者的专家访谈以及 12 个案例研究的分析。我们的研究确定了五个核心主题，将生成式 UI 定位为迭代和协同创造的过程。我们强调了新兴的设计模型，包括混合创作、基于策展的工作流程和 AI 辅助的优化策略。此外，我们还考察了塑造该领域的伦理挑战、评估标准和交互模型。通过提出一个概念基础，这项研究推进了理论探讨和实践应用，引导未来人机交互研究走向负责任和有效的生成式用户界面设计实践。

Generative UI; User Interface Design; AI-driven Design; Generative Design; Computational Creativity; Responsible AI  
生成式 UI；用户界面设计；AI 驱动设计；生成式设计；计算创造力；负责任的 AI

## 1\. Introduction 1.引言

The landscape of User Interface (UI) design is experiencing a profound transformation driven by recent advances in generative artificial intelligence (GenAI) [^26]. Once the exclusive domain of human designers working with static design tools like Adobe Creative Suite [^28], UI creation is increasingly becoming a collaborative process where AI systems actively generate, refine, and even evaluate design solutions. This shift is not merely an expansion of the designer’s toolset— it represents a fundamental reconfiguration of the design process itself, challenging long-established paradigms and notions of creativity, authorship, and human-computer collaboration in user interface (UI) design [^54] [^12] [^50] [^7]. In recent years, there has been an unprecedented increase in both research interest and commercial applications using generative capabilities for UI design. Large language models such as GPT-4 [^43] and Claude [^2] have demonstrated the ability to generate functional GUI code and design specifications. These technologies have rapidly moved from research-level outputs to production tools, with AI assistants like GitHub Copilot [^25], Cursor.ai [^18], or Bolt.new [^10] embedding generative capabilities directly into professional design workflows. The result is a growing ecosystem where designers are increasingly collaborating with GenAI systems that can generate, refine, and implement design solutions at unprecedented speed and scale, even called vibe coding [^46].  
用户界面（UI）设计领域正经历着由生成式人工智能（GenAI）最新进展驱动的深刻变革（Goodfellow 等人，2014）。曾经是人类设计师使用静态设计工具（如 Adobe Creative Suite（公司，2025））工作的专属领域，UI 创建正日益成为一个协作过程，其中人工智能系统主动生成、完善甚至评估设计方案。这种转变不仅仅是设计师工具集的扩展——它代表了设计过程本身的根本性重构，挑战了用户界面（UI）设计中长期确立的范式和创造力、作者身份以及人机协作的观念（Yang 等人，2020；Carroll 等人，1988a；Stone 等人，2005；Blair-Early 和 Zender，2008）。近年来，使用生成能力的研究兴趣和商业应用都出现了前所未有的增长。UI 设计领域。大型语言模型如 GPT-4（OpenAI，2025 年）和 Claude（AI，2025 年）已展示出生成功能 GUI 代码和设计规范的能力。这些技术迅速从研究级输出转变为生产工具，GitHub Copilot（GitHub，2025 年）、Cursor.ai（Cursor，2025 年）或 Bolt.new（Bolt，2025 年）等 AI 助手将生成能力直接嵌入专业设计工作流程中。结果是日益壮大的生态系统，设计师越来越多地与能够以前所未有的速度和规模生成、优化和实施设计解决方案的 GenAI 系统合作，甚至被称为 vibe 编程（Ray，2025 年）。

Despite this rapid technological advancement and practical adoption, the conceptual understanding of ”Generative UI (GenUI)” and ”the design practices of GenUIs” remains underdeveloped. The current understandings of UI/UX issues for generative AI [^32] or intelligent user interfaces [^4] focus on technological advancements to enable GenUI design practices, static artifact generation or inference mechanisms and algorithms to monitor user actions, interactions, offering limited insight into the design-time, co-creative, and dialogic processes that define and characterize GenUI. This theoretical gap creates potential limitations for researchers investigating generative UI design phenomena and practitioners seeking to develop effective workflows that incorporate these new capabilities under a unified concept and shared conceptual working definitions.  
尽管在技术进步和实际应用方面取得了飞速发展，但“生成式 UI（GenUI）”和“GenUI 的设计实践”的概念理解仍然不足。当前对生成式 AI（Kim 等人，2024 年）或智能用户界面（Alvarez-Cortes 等人，2007 年）的 UI/UX 认知主要关注技术进步以支持 GenUI 设计实践、静态工件生成或用于监控用户行为、交互的推理机制和算法，而这些认知对定义和表征 GenUI 的设计时、协同创作和对话式过程缺乏洞察。这种理论上的差距为研究生成式 UI 设计现象的研究人员以及寻求在统一概念和共享概念工作定义下整合这些新能力的从业者带来了潜在的限制。

From this perspective, this position paper addresses a conceptual gap by proposing a working definition of GenUIs and the design of GenUIs as a distinct design paradigm. Based on a systematic synthesis of academic literature, practitioner insights, and case analyses, we identify five constitutive elements that differentiate GenUI from both traditional UI design: computational co-creation, expanded design space exploration, representation fluidity, contextual adaptation, and synthesis over selection. Our findings suggest that GenUI is a new mode of interface creation that emphasizes design-time collaboration between human and machine agents and run-time user interaction with AI-generated GUI variants.  
从这一角度来看，这份立场文件通过提出 GenUIs 的工作定义以及将 GenUIs 设计为一种独特的设计范式来填补一个概念上的空白。基于对学术文献、从业者见解和案例分析的系统性综合，我们确定了五个构成要素，这些要素区分了 GenUI 与传统 UI 设计的不同之处：计算式共创、扩展设计空间探索、表现流体性、情境适应以及综合而非选择。我们的研究结果表明，GenUI 是一种新的界面创建模式，它强调设计时人类与机器代理之间的协作以及运行时用户与 AI 生成的 GUI 变体的交互。

By providing this working definition, we aim to support the DIS community’s ongoing efforts to understand and effectively leverage the transformative potential of generative AI, particularly in interface design. We believe that this conceptual clarity will become increasingly significant as generative approaches transition from experimental applications to mainstream design practices, fundamentally altering how interfaces are created, experienced, and adapted in response to user needs.  
通过提供这个工作定义，我们旨在支持 DIS 社区持续努力理解和有效利用生成式 AI 的变革潜力，特别是在界面设计中。我们相信，随着生成式方法从实验性应用过渡到主流设计实践，这种概念上的清晰度将变得越来越重要，从根本上改变界面创建、体验和适应用户需求的方式。

## 2\. Related Work 2.相关工作

Regarding the use of Generative AI for Design, GenAI represents a paradigm shift in computational systems, moving from analytical to creative capabilities. GenAI models learn from large datasets, identifying underlying patterns and structures. This allows the models to create new content that resembles the training data [^26]. Also, attention mechanisms, which allow models to focus on relevant parts of the input data. This is crucial for generating coherent and contextually accurate outputs, especially in tasks involving sequences [^52].  
关于使用生成式 AI 进行设计，生成式 AI 代表了计算系统的一个范式转变，从分析能力转向创造能力。生成式 AI 模型通过学习大型数据集来识别底层模式和结构。这使得模型能够创建与训练数据相似的新内容（Goodfellow 等人，2014 年）。此外，注意力机制允许模型专注于输入数据的相关部分。这对于生成连贯且上下文准确的输出至关重要，特别是在涉及序列的任务中（Vaswani 等人，2017 年）。

With the characteristics, the application of GenAIs to design disciplines has evolved rapidly over the past decade. Early explorations focused on relatively constrained generative systems for specific design tasks, such as typography generation [^11], layout optimization [^42], and color palette suggestion [^33], rather than being applied to the design of user interface tasks. These systems typically operated within narrowly defined parameters and required substantial human supervision. More recent advances have dramatically expanded both the scope and autonomy of generative design systems, enabling them to produce complex, multi-faceted design artifacts with minimal human guidance [^35] [^15] [^14] [^45].  
凭借其特性，过去十年中，GenAI 在设计学科中的应用发展迅速。早期的探索主要集中在相对受限的生成系统上，用于特定的设计任务，例如字体生成（Campbell and Kautz, 2014）、布局优化（O’Donovan et al, 2015）和色彩板建议（Kita and Miyata, 2016），而不是应用于用户界面任务的设计。这些系统通常在狭义定义的参数内运行，并需要大量的人工监督。最近的进展显著扩展了生成设计系统的范围和自主性，使它们能够在最小的指导下产生复杂、多方面的设计工件（Matejka et al, 2018; Chen and Zhang, 2019; Chen et al, 2020; Ramesh et al, 2021）。

Interestingly, it is considered that the concept of Generative Design precedes current GenAI implementations, with roots in various design traditions that emphasize procedural or rule-based creation. In architecture and industrial design, generative design has historically referred to approaches that use algorithms to explore design spaces constrained by specified parameters and objectives [^22]. For example, Oxman’s taxonomy of digital design [^44] distinguishes between parametric design (manipulation of variables within a fixed system), algorithmic design (rule-based procedures), and truly generative approaches where emergent properties arise from system interactions.  
有趣的是，人们认为生成式设计概念早于当前的 GenAI 实现，其根源在于各种强调程序化或基于规则的创造的设计传统。在建筑和工业设计中，生成式设计历史上指的是使用算法探索受指定参数和目标限制的设计空间的方法（Fischer 和 Herr，2001）。例如，Oxman 的数字设计分类法（Oxman，2006）区分了参数化设计（在固定系统内操纵变量）、算法设计（基于规则的程序）以及真正的生成式方法，其中涌现属性源于系统交互。

In creative fields, in a broad manner, generative methodologies have been conceptualized through various theoretical frameworks. For instance, Gero’s Function-Behavior-Structure model [^24] provides a lens for understanding how generative systems navigate from functional requirements to structural design solutions. Cross’ designerly ways of knowing [^17] emphasizes the distinct epistemological approaches that characterize design thinking, many of which present challenges for computational implementation. Dorst’s frame creation [^20] offers insights into how designers reframe problems—a critical creative capability that current generative systems struggle to replicate.  
在创意领域，广义而言，生成性方法论通过各种理论框架得到了概念化。例如，Gero 的功能-行为-结构模型（Gero 和 Kannengiesser，2004）提供了一个视角，用于理解生成性系统如何从功能需求导航到结构设计解决方案。Cross 的设计师认知方式（Cross，1982）强调了设计思维所特有的不同认识论方法，其中许多方法对计算实现提出了挑战。Dorst 的框架创建（Dorst，2011）为设计师如何重新框架问题提供了见解——这是当前生成性系统难以复制的关键创造性能力。

Computational creativity research offers additional perspectives relevant to generative UI. Boden’s conceptualization of creativity as exploratory, combinatorial, or transformational [^9] provides a useful framework for evaluating the creative capabilities of generative UI systems. Colton’s creative tripod model [^16], emphasizing skill, appreciation, and imagination as essential components of computational creativity, suggests criteria for assessing the sophistication of generative design tools. Within the HCI research, several theoretical frameworks inform understanding of generative approaches. Reflection-in-action, as articulated by Schön [^47], captures the iterative, conversational nature of design processes that effective generative UI systems must support. Participatory design traditions [^37] raise important questions about how generative tools redistribute agency between designers, systems, and end-users. User-centered design methodologies [^23] [^5] emphasize empirical user research as a foundation for design decisions—an aspect often underdeveloped in current generative approaches.  
计算创造力研究为生成式 UI 提供了额外的相关视角。Boden 将创造力概念化为探索性、组合性或转换性（Boden，2004），为评估生成式 UI 系统的创造力提供了有用的框架。Colton 的创造力三脚架模型（Colton，2008），强调技能、欣赏和想象力作为计算创造力的基本组成部分，提出了评估生成式设计工具复杂性的标准。在 HCI 研究中，几个理论框架指导着对生成式方法的理解。Schön 阐述的“行动中反思”（Schön，2017）捕捉了设计过程的迭代、对话性质，而有效的生成式 UI 系统必须支持这种性质。参与式设计传统（Muller 和 Kuhn，1993）提出了关于生成式工具如何在设计师之间重新分配能动性的重要问题。系统，以及最终用户。以用户为中心的设计方法论（Gasson，2003；Anderson，1988）强调将实证用户研究作为设计决策的基础——这一方面在当前生成式方法中往往发展不足。

Building on these insights, our research draws from foundational concepts to explore how GenUI systems function as generative, dialogic partners in the design process. By integrating these theoretical foundations with empirical analyses of expert interviews and case studies, we develop a working definition and dimensional framework for GenUI that clarifies how it differs from prior user interface design paradigms. The proposed framework aims to guide future inquiries into how generative tools reshape interface design at both conceptual and operational levels.  
基于这些见解，我们的研究借鉴基础概念，探讨 GenUI 系统如何在设计过程中作为生成性、对话性伙伴发挥作用。通过将这些理论基础与专家访谈和案例研究的实证分析相结合，我们为 GenUI 制定了一个工作定义和维度框架，阐明了它与先前用户界面设计范式有何不同。所提出的框架旨在指导未来对生成工具如何重塑界面设计在概念和操作层面的研究。

## 3\. Identifying Gaps in Literature3.文献中的空白识别

![Refer to caption](https://arxiv.org/html/2505.15049v1/x1.png)

Figure 1. A summary of user interface design paradigms based on design attributes 31 13 39 30 27 图 1. 基于设计属性的用户界面设计范式总结 (Jansen, 1998; Carroll 等人, 1988b; Myers, 2001; Jameson, 2007; Horvitz, 1999)

Despite this rich theoretical landscape, existing definitions and frameworks potentially fall short in addressing the unique characteristics of generative UI design. Current conceptualizations of generative design could not specifically fit into to account for several critical aspects of UI-specific applications as follows: First, the interactive nature of UI artifacts introduces unique challenges and opportunities not present in static design domains. Unlike generative art or architectural form-finding, UI generation must consider not only visual aesthetics but also interaction flows, state transitions, and real-time responsiveness to user input [^8] [^3].  
尽管拥有丰富的理论背景，现有的定义和框架在应对生成式 UI 设计的独特特性方面可能存在不足。当前关于生成式设计的概念化理解难以具体适应 UI 特定应用的几个关键方面，具体如下：首先，UI 实物的交互特性带来了静态设计领域不存在的独特挑战和机遇。与生成式艺术或建筑形态寻找不同，UI 生成不仅要考虑视觉美学，还必须考虑交互流程、状态转换以及实时响应用户输入（Blom 和 Beckhaus，2014；Altakrouri 和 Schrader，2012）。

Current generative design frameworks rarely address these dynamic aspects adequately. Second, UI design operates within particularly complex constraint ecosystems, including technical implementation limitations, accessibility requirements, cross-platform compatibility, and evolving design systems [^56]. Generative approaches must navigate these constraints while maintaining creative flexibility. Third, the collaborative nature of contemporary UI design processes, involving multiple stakeholders with diverse expertise, creates distinct requirements for generative tools [^29]. Unlike domains where a single designer can work with generative systems, for instance, graphic design or illustration, UI design typically involves cross-functional teams whose collaborative dynamics are significantly altered by the introduction of generative capabilities. Finally, the rapid evolution of GenUI technologies has created a disconnection between theoretical understanding and practical implementation. Industry adoption has outpaced academic conceptualization, resulting in a terminology gap where practitioners and researchers lack a shared vocabulary to discuss emerging phenomena [^55].  
当前的生成式设计框架很少充分解决这些动态方面。其次，UI 设计在特别复杂的约束生态系统中运作，包括技术实现限制、无障碍要求、跨平台兼容性以及不断发展的设计系统（Zhu 等人，2018 年）。生成式方法必须在保持创意灵活性的同时应对这些约束。第三，当代 UI 设计过程的协作性质，涉及具有不同专业知识的多个利益相关者，为生成式工具创造了独特的需求（Inie 和 Dalsgaard，2020 年）。与单一设计师可以与生成式系统合作的设计领域不同，例如平面设计或插画，UI 设计通常涉及跨职能团队，其协作动态会受到引入生成式能力的显著影响。最后，GenUI 技术的快速演变已经造成了理论理解与实践应用之间的脱节。行业采用速度超过了学术概念化，导致术语差距，从业者与研究者在讨论新兴现象时缺乏共同词汇（Yang 等人，2019）。

To clarify the conceptual distinctiveness of GenUI, we present a comparative framework situating GenUI within the historical evolution of interface paradigms—from traditional graphical user interfaces to customizable, adaptive, and intelligent systems as shown in Figure 1. This chronological structure provides a historical narrative: from early symbolic GUIs (e.g., WIMP interfaces) to user-configurable systems, then to system-adaptive and intelligent behaviors, and finally to co-creative design-time systems. It offers a theoretical ground that GenUI represents a paradigm shift in how interfaces are designed, not just how they operate, enabled by technological advances through conceptual dimensions.  
为阐明 GenUI 的概念独特性，我们提出一个比较框架，将 GenUI 置于界面范式的历史演变之中——从传统的图形用户界面到可定制、自适应和智能系统，如图 1 所示。这种时间结构提供了一个历史叙事：从早期的符号 GUI（例如 WIMP 界面）到用户可配置系统，然后到系统自适应和智能行为，最后到协同创意的设计时系统。它为 GenUI 代表了一种范式转变提供了理论基础，这种转变不仅在于界面的操作方式，还在于其设计方式，这是通过概念维度中的技术进步实现的。

The interface design attributes used in Figure 1 to differentiate user interface paradigms are grounded in well-established HCI theory. For example, interaction control draws from Norman’s action cycle [^41], which models how users form goals, execute actions, and evaluate outcomes, thus framing how control is distributed between human and system. Representation fidelity builds on Shneiderman’s [^48] [^49] visual information-seeking mantra and Nielsen’s [^40] and Whiteside et al.’s [^53] heuristic of system visibility, emphasizing the importance of interfaces that transparently reflect internal states. Dix et al.’s interaction framework informs temporal context [^19], distinguishing between design-time and runtime processes in user interaction. Design responsibility is situated within Fischer and Giaccardi’s [^21] meta-design paradigm, which examines how co-creation distributes creative authority across human and machine agents. Adaptivity and plasticity emerge from Thevenin and Coutaz’s [^51] work on user interface plasticity and Myers’s [^38] historical analysis of flexible UI technologies. Finally, explorability and feedback are rooted in Nielsen’s [^40] emphasis on user control and Shneiderman’s [^48] advocacy for direct manipulation. At the same time, system agency and initiative are extended from Jameson’s [^30] and Horvitz’s [^27] models of proactive, intelligent interfaces.  
图 1 中用于区分用户界面范式的界面设计属性基于成熟的 HCI 理论。例如，交互控制借鉴了诺曼的行动循环（Norman，1986），该模型描述了用户如何形成目标、执行动作和评估结果，从而界定了控制和系统之间的分配方式。表示保真度建立在施耐德曼（Shneiderman，1983，2003）的可视信息搜索箴言和尼尔森（Nielsen，1994）以及怀特塞德等人（Whiteside et al，1988）的系统可见性启发式方法之上，强调了透明反映内部状态的界面的重要性。迪克斯等人的交互框架提供了时间上下文（Dix，2010），区分了用户交互中的设计时和运行时过程。设计责任位于费舍尔和吉卡迪的元设计范式（Fischer et al，2004）之中，该范式探讨了协同创造如何运作。n 将创意授权分配给人类和机器代理。适应性及可塑性源于 Thevenin 和 Coutaz（Thevenin and Coutaz, 1999）对用户界面可塑性的研究以及 Myers（Myers, 1998）对灵活 UI 技术的历时性分析。最后，可探索性和反馈根植于 Nielsen（Nielsen, 1994）对用户控制的强调以及 Shneiderman（Shneiderman, 1983）对直接操作的倡导。与此同时，系统代理和主动性扩展自 Jameson（Jameson, 2007）和 Horvitz（Horvitz, 1999）的主动式智能界面模型。

Together, these dimensions offer a theoretical lens for understanding the unique position of GenUI within the evolution of interface paradigms - GenUI is not just oriented toward generating design artifacts but also alters user experience during runtime according to user preferences and contexts. The dimensions, such as interaction control, temporal logic, and system agency, help us to better understand how these systems operate at runtime and what they produce at design time.  
这些维度共同提供了一个理论视角，用于理解 GenUI 在界面范式演变中的独特地位——GenUI 不仅面向生成设计工件，还在运行时根据用户偏好和上下文改变用户体验。这些维度，如交互控制、时序逻辑和系统代理，帮助我们更好地理解这些系统在运行时的运作方式以及它们在设计时产生的内容。

## 4\. Research Methods 4. 研究方法

We employed a multi-method qualitative approach to develop a working definition of generative UI, integrating theoretical perspectives with emerging practices. Our research consisted of four components: a systematic literature review, expert interviews, case study analysis, and community discourse.  
我们采用了一种多方法定性方法来开发生成式 UI 的工作定义，将理论视角与新兴实践相结合。我们的研究由四个部分组成：系统文献综述、专家访谈、案例研究分析和社区讨论。

First, we conducted a systematic literature review using an adapted PRISMA protocol [^36]. Our objective was to trace how generative approaches have been conceptualized and applied within the context of UI design, and to distinguish GenUI from historical paradigms such as adaptive, customizable, personalizable, intelligent,ai-assisted, and generative interfaces. We searched major digital databases—including the ACM Digital Library, IEEE Xplore, and Google Scholar—using search terms: combining historical paradigms keyword + relevant keywords as suffix (user interface, design, interaction, system) respectively. Our inclusion criteria focused on publications from 1982 (in 1982 CHI was organised for the first time) to December 2024 to capture both foundational user interface concepts and recent advances in generative AI for interface design.  
首先，我们使用改进的 PRISMA 协议（Moher 等人，2010 年）进行了一项系统性的文献综述。我们的目标是追踪生成式方法如何在 UI 设计背景下被概念化和应用，并区分 GenUI 与历史范式，如自适应、可定制、可个性化、智能、AI 辅助和生成式界面。我们使用搜索词：结合历史范式关键词 + 相关关键词作为后缀（用户界面、设计、交互、系统）分别搜索了主要数字数据库——包括 ACM 数字图书馆、IEEE Xplore 和 Google Scholar。我们的纳入标准集中于 1982 年（1982 年 CHI 首次举办）至 2024 年 12 月的出版物，以捕捉基础用户界面概念和生成式 AI 在界面设计中的最新进展。

Our initial search yielded 1,213 records. After removing duplicates and screening titles and abstracts for relevance, we excluded 932 records that did not directly address interface or user interaction design. The exclusion criteria applied were as follows: (1) papers primarily focused on developing algorithms rather than design; (2) papers that described generative systems in less relevant domains (e.g., architecture, art) without addressing interactive systems; and (3) papers primarily focused on building generative AI models without a design-oriented framework/intepretation. A remaining set of 281 papers underwent a full-text review.  
我们的初步搜索产生了 1,213 条记录。在删除重复项并对标题和摘要进行相关性筛选后，我们排除了 932 条未直接涉及界面或用户交互设计的记录。排除标准如下：(1) 主要关注算法开发而非设计的论文；(2) 描述了在不太相关的领域（例如建筑、艺术）中生成的系统，而没有涉及交互系统的论文；以及 (3) 主要关注构建生成式 AI 模型，但没有设计导向框架/解释的论文。剩余的 281 篇论文接受了全文审查。

Lastly, we conducted an open coding process on the final corpus of 127 papers. Initial codes were clustered inductively into conceptual categories, including design agency, representational mechanisms, system initiative, iteration logic, and contextual constraint handling. Through iterative refinement through triangulation, we synthesized these categories into five core dimensions differentiating GenUI: computational co-creation, expanded design space exploration, representation fluidity, contextual adaptation, and synthesis over selection. These dimensions informed the construction of our working definition and comparative framework, anchoring our contribution within both empirical insights and theoretical lineage in HCI and design studies.  
最后，我们对 127 篇论文的最终语料库进行了开放式编码。初始编码通过归纳方法聚类成概念类别，包括设计代理、表征机制、系统主动性、迭代逻辑和情境约束处理。通过三角测量法的迭代精炼，我们将这些类别综合为五个区分 GenUI 的核心维度：计算式共创、扩展设计空间探索、表征流动性、情境适应和选择之上的综合。这些维度指导了我们工作定义和比较框架的构建，将我们的贡献锚定在 HCI 和设计研究中的实证见解和理论谱系之中。

To complement the systematic literature review results with practitioner perspectives, we conducted semi-structured interviews with 18 experts: HCI researchers at a university (n=6), UI/UX designers using generative tools (n=7), and generative UI developers (n=5). Participants, aged 27–48 (M=36.4, SD=7.8), had an average of 3.3 years of experience with generative AI. Interviews (18.6 total hours in total, 8,167 words in each interview) explored definitions, implementation experiences, benefits, limitations, and future expectations, transcribed and analyzed using our coding framework.  
为了补充系统性文献综述结果与实践者的观点，我们与 18 位专家进行了半结构化访谈：大学的人机交互（HCI）研究人员（n=6）、使用生成式工具的 UI/UX 设计师（n=7）以及生成式 UI 开发者（n=5）。参与者年龄在 27 至 48 岁之间（平均年龄 36.4 岁，标准差 7.8 岁），平均具有 3.3 年的生成式 AI 使用经验。访谈（总时长 18.6 小时，每次访谈 8,167 字）探讨了定义、实施经验、优势、局限性和未来预期，并使用我们的编码框架进行转录和分析。

Additionally, we analyzed 12 case studies from participants’ former/current projects, covering experimental research systems (8), AI-assisted mobile app prototypes, and enterprise platforms (2) for image content generation (2). We examined how generative capabilities were conceptualized, implemented, and integrated into professional UI design workflows. Data analysis, conducted in ATLAS.ti, used affinity diagramming to identify themes and conceptual relationships. To enhance validity, we conducted member checking with eight interviewees, incorporating their feedback into the final definition. The methodological approach described above enabled us to develop a working definition that reflects both theoretical rigor and practical relevance. By synthesizing perspectives from literature, expert practitioners, implemented systems, and community discourse, we aimed to create a definition with broad applicability across research and practice contexts within the evolving field of generative UI design.  
此外，我们分析了参与者过去/当前项目的 12 个案例研究，涵盖实验性研究系统（8 个）、AI 辅助的移动应用原型和企业平台（2 个）用于图像内容生成（2 个）。我们考察了生成能力如何被概念化、实现并集成到专业 UI 设计工作流程中。在 ATLAS.ti 中进行的数据分析使用了亲和图法来识别主题和概念关系。为了提高有效性，我们对八位访谈对象进行了成员检查，并将他们的反馈纳入最终定义中。上述方法论使我们能够制定一个既反映理论严谨性又具有实践相关性的工作定义。通过综合来自文学、专家实践者、已实施系统以及社区讨论的视角，我们旨在创建一个在生成式 UI 设计这一不断发展的领域中，对研究和实践环境具有广泛适用性的定义。

## 5\. Findings 5. 研究结果

### 5.1. The Working Definition of Designing Generative UI5.1. 可生成式 UI 设计的工作定义

Our systematic analysis revealed several key themes that collectively characterize the emerging domain of generative user interface design. We propose the following working definition of a Generative User Interface: it is a user interface that is created, refined, or evolved through computational generative processes, where AI systems contribute to the design, implementation, or adaptation of the interface. This approach ensures that the interface accurately captures, analyzes, and implements user values, resulting in interfaces that are not only technically functional but also meaningfully aligned with users’ actual values as suggested by [^56]. These interfaces emerge from collaborative creation between human designers, AI assist tools and agents, and the final users, rather than being solely manually crafted through traditional design process and deliver to the final users.  
我们的系统性分析揭示了几个关键主题，这些主题共同描绘了生成式用户界面设计的新兴领域。我们提出生成式用户界面的工作定义：它是一个通过计算生成过程创建、完善或演变的用户界面，其中人工智能系统为界面的设计、实施或适应做出贡献。这种方法确保界面能够准确捕捉、分析和实现用户价值，从而产生不仅技术功能强大，而且与用户实际价值（如 Zhu 等人，2018 年所暗示）有意义的对齐的界面。这些界面源于人类设计师、人工智能辅助工具和代理以及最终用户之间的协作创造，而不是通过传统的手动设计过程单独制作并交付给最终用户。

Under this context, Designing Generative UI refers to a computational co-creation process in which designers and AI systems collaboratively explore, synthesize, and refine user interfaces. This is achieved through bidirectional translation between representational forms, context-aware pattern generation, and iterative evaluation against human and technical requirements. This approach enhances the design process by facilitating collaboration between humans and computational agents (AI systems), thereby expanding the design spaces that can be explored in the latent space, which is informed by data. Additionally, it allows for rapid adaptation to evolving situated design problems in a non-linear manner. This definition encompasses both the technological components of generative UI—such as computational pattern generation and multi-modal representation—and the socio-technical processes through which these capabilities are implemented, including co-creation, distributed agency, and iterative evaluation.  
在此背景下，“设计生成式 UI”指的是设计师和 AI 系统共同探索、合成和细化用户界面的计算协同创作过程。这是通过在表征形式之间进行双向转换、基于上下文的模式生成以及针对人类和技术需求的迭代评估来实现的。这种方法通过促进人类与计算代理（AI 系统）之间的协作，增强了设计过程，从而扩展了可以在数据指导下探索的潜在空间，同时还允许以非线性方式快速适应不断变化的情境设计问题。此定义涵盖了生成式 UI 的技术组件——例如计算模式生成和多模态表示——以及这些功能实施的社会技术过程，包括共创、分布式代理和迭代评估。

- Computational Co-Creation:Generative UI fosters a human-AI partnership rather than full automation. Unlike earlier visions of design automation that positioned computational systems as eventually replacing human designers, current understanding emphasizes human-AI partnership in what several interview participants described as ”human-AI co-creation” or ”augmented design intelligence.” As one expert UI designer explained, ”It’s not about the AI taking over design work, but rather establishing a creative dialogue. I provide direction, constraints, and critical evaluation, while the generative system offers multiple variations, possibilities, and sometimes surprising alternatives I wouldn’t have considered.” (P9, Senior Designer)
	  
	• 计算协同创作：生成式 UI 促进了人机合作，而非完全自动化。与早期设计自动化愿景中将计算系统定位为最终取代人类设计师不同，当前理解强调人机合作，多位访谈参与者将其描述为“人机协同创作”或“增强设计智能”。正如一位资深 UI 设计师解释的那样，“这并非 AI 接管设计工作，而是建立创意对话。我提供方向、约束和批判性评估，而生成式系统提供多种变化、可能性和有时是我未曾考虑到的惊人替代方案。”（P9，资深设计师）
- Expanded Design Space Exploration: another consistent theme was generative UI’s capacity to facilitate exploration of expanded design spaces in complex possibility spaces as suggested [^9]. Traditional UI design processes often converge prematurely on familiar solutions due to time constraints, cognitive biases, or limited design vocabulary as noted \[31\]. Generative approaches enable broader exploration by rapidly producing diverse alternatives, including options that might fall outside a designer’s typical patterns. This was particularly emphasized in case study examples, where systems like Uizard’s UI generation features or Cursor.ai assistant tools were positioned as tools for expanding creative possibilities rather than merely accelerating production of predetermined designs. One research publication characterized this as ”computational divergent thinking” [^34], suggesting that this computational variations couldn’t replace human creativity as we still evaluate its quality and relevance to the project but amplifies it by suggesting unexpected directions.
	  
	• 扩展设计空间探索：另一个一致的主题是生成式 UI 的能力，能够促进在复杂可能性空间中对扩展设计空间的探索，正如 Boden（2004）所建议的那样。传统的 UI 设计过程往往由于时间限制、认知偏差或有限的设计词汇而过早地收敛于熟悉的解决方案，如\[31\]所述。生成式方法通过快速生成多样化的替代方案来促进更广泛的探索，包括那些可能超出设计师典型模式的选项。这在案例研究示例中尤其被强调，其中像 Uizard 的 UI 生成功能或 Cursor.ai 助手工具这样的系统被定位为扩展创意可能性的工具，而不仅仅是加速预定设计的生产。一项研究出版物将其描述为“计算式发散思维”（Krish，2011）。表明这种计算变化并不能取代人类创造力，因为我们仍然评估其质量和与项目的相关性，但它通过建议意想不到的方向来增强它。
- Representation Fluidity: Unlike linear UI design workflows, generative UI allows seamless movement between sketches, wireframes, visual designs, and functional code. Tools like Uizard and Galileo AI facilitate this multi-modal design synthesis, accelerating such iteration. This bidirectional translation between representations emerged as a distinctively generative capability, contrasting with traditional tools that typically operate within a single representational domain. As one system developer noted: ”What makes current generative UI truly revolutionary is this ability to jump between ideation, written product requirement document texts, and code almost instantaneously. A designer can describe an interaction pattern in words, immediately see visual alternatives, refine through direct manipulation, and then export functional code—all within minutes instead of days.” (P15, AI Tool Developer)
	  
	• 表示流畅性：与线性 UI 设计工作流程不同，生成式 UI 允许在草图、线框图、视觉设计和功能代码之间无缝切换。Uizard 和 Galileo AI 等工具促进了这种多模态设计合成，加速了此类迭代。这种表示之间的双向转换已成为一种独特的生成能力，与通常在单一表示域内操作的传统工具形成对比。正如一位系统开发者所说：“当前生成式 UI 真正革命性的地方在于这种能够在构思、产品需求文档文本和代码之间几乎瞬间切换的能力。设计师可以用文字描述交互模式，立即看到视觉替代方案，通过直接操作进行完善，然后导出功能代码——所有这一切都在几分钟内完成，而不是几天。”（第 15 页，AI 工具开发者）
- Contextual Adaptation: Generative UI adapts to brand guidelines, accessibility standards, user preferences, and cultural factors, demonstrating an implicit design knowledge that refines outputs dynamically beyond explicit rules. One research paper characterized this as ”implicit design knowledge” that enables generative systems to make nuanced contextual adjustments that would be difficult to explicitly codify [^6]. One of the interviewees described: ”I’ve built a collection of prompt templates with the blank for different design scenarios—one for creating initial explorations of a new feature, another for generating variations on an existing component, others for adapting designs across different design issues. Each template includes specific language and expressions that I’ve found effectively communicates my design intent to the AI.” (P7, Product Designer)
	  
	• 上下文适应：生成式 UI 会适应品牌指南、无障碍标准、用户偏好和文化因素，展现出一种隐含的设计知识，使其能够动态地优化输出，超越明确的规则。一篇研究论文将此描述为“隐含的设计知识”，它使生成系统能够进行细微的上下文调整，而这些调整很难用明确的规则来编码（Becker 等人，2021）。一位受访者描述道：“我建立了一个包含空白模板的提示集合，用于不同的设计场景——一个用于创建新功能的初步探索，另一个用于生成现有组件的变体，还有其他用于跨不同设计问题调整设计。每个模板都包含我发现的能够有效地向 AI 传达我的设计意图的特定语言和表达。”（P7，产品设计师）
- Design Synthesis Over Selection: The final theme involved the shift from selection-based to synthesis-based design processes. Traditional digital design tools primarily offer selection from predefined design options or with specific user scenario for designers to create genuinely novel elements from the scratch. Generative UI approaches, by contrast, enable continuous synthesis of new design possibilities through recombination and transformation embracing various design issues. As one GUI designer explained: ”Before, my design process felt like IKEA shopping — selecting from available options and assembling them. With generative tools, it’s more like cooking — I’m combining ingredients with a general recipe in mind with my own kicks, but I know the specific outcome emerges through the process. I’m still making creative decisions, but they’re higher-level directional choices rather than selections from limited menus.” (P3, UX Director)
	  
	• 设计综合优于选择：最终的主题涉及从基于选择到基于综合的设计流程的转变。传统的数字设计工具主要提供从预定义设计选项中选择或针对特定用户场景进行设计，让设计师能够从零开始创造真正新颖的元素。相比之下，生成式 UI 方法通过重组和转换，融合各种设计问题，实现新设计可能性的持续综合。正如一位 GUI 设计师解释的那样：“以前，我的设计流程感觉像在宜家购物——从现有选项中选择并组装。有了生成式工具，这更像是在烹饪——我带着一个大致的食谱，结合自己的风格，混合各种食材，但我知道具体的结果是通过这个过程产生的。我仍然在做创意决策，但这些是更高层次的指导性选择，而不是从有限的菜单中进行选择。””(P3, 用户体验总监)”
- Gaps in Runtime Adaptation to User Values: While GenUI systems possess the technical ability to synthesize interface variants based on high-level parameters—such as device constraints, accessibility requirements, or use-case descriptors—these capabilities are often underutilized or externally specified, rather than embedded into the generative logic itself. Prompt engineering and iterative refinement remain centered on designer intent, aesthetic variation, and structural efficiency, but rarely incorporate dynamic user needs or runtime context (e.g., task urgency, preferred user values, contextual constraints) as first-class design considerations so far. This creates a disconnect between the AI system’s generative power and the situated nature of user interaction, ultimately limiting the alignment between generative outputs and end-user goals and values. For example, ”I know the GenAI system can generate a bunch of variants in my end, but I never thought about how to get it to reflect what the user needs and what s/he wants to see in the real-time context. It still feels like I am utilizing a traditional design and deployment process.” (P3, UX Director)
	  
	• 在运行时适应用户价值方面的差距：虽然 GenUI 系统具备根据高级参数（如设备约束、无障碍要求或用例描述）合成界面变体的技术能力，但这些能力通常未被充分利用或由外部指定，而不是嵌入到生成逻辑本身中。提示工程和迭代优化仍然以设计者的意图、美学变化和结构效率为中心，但很少将动态用户需求或运行时上下文（例如，任务紧急性、首选用户价值、上下文约束）作为首要的设计考虑因素。这造成了 AI 系统的生成能力与用户交互的情境性之间的脱节，最终限制了生成输出与最终用户目标和价值的一致性。例如，“我知道 GenAI 系统可以在我的端生成大量变体”但我从未想过如何让它反映用户的需求以及他们在实时环境中所想看到的。这仍然让我感觉像是我在使用传统的设计和部署流程。”（P3，用户体验总监）

### 5.2. Challenges Ahead

Our research identified key challenges and open questions in the design and the use of generative UIs, spanning ethical, technological, and professional concerns. These issues demand further exploration by the HCI community to shape the responsible evolution of this field.

- Value prioritization and balance: The generative approach creates a more direct pathway from value articulation to design implementation, reducing the ”value drift” that often occurs in traditional design processes where initial insights become diluted through multiple translation stages. Also, by formally extracting and representing values, GenUI systems should be able to effectively handle complex value trade-offs, recognizing when certain values represent boundary constraints while others are optimization targets within those boundaries.
- Bias and Representation: Generative systems learn from historical design data, inheriting and potentially amplifying biases related to gender, culture, and accessibility. Without intervention, these biases may persist in AI-generated outputs.
- Attribution and Intellectual Property: Generative UI challenges traditional notions of authorship and ownership. When AI plays a central role in creation, who receives credit—the designer, the AI, or both? Many practitioners struggle to showcase their contributions when AI handles much of the visible production
- Functional Accuracy in Interactive Contexts: Unlike static UI designs, GenUIs should be able to function correctly across states and user flows. Current generative models often create interfaces that look correct but fail in usability or interaction logic.
- Integration with Existing Design Workflows: Most generative tools remain siloed, requiring context-switching between AI-driven interfaces and traditional design platforms being serviced. Seamless integration and transition is essential for broader adoption but remains technically challenging.

### 5.3. Future Research Direction

#### 5.3.1. Designing Together: Supporting Collaboration Between Humans and Generative Systems

The findings synthesized through our research reveal that GenUI reconfigures traditional boundaries of interaction control, design responsibility, and system agency. Unlike earlier paradigms—where systems were either passive instruments (GUI, customizable UI) or reactive entities (AUI/IUI)—GenUI tools engage in bidirectional exchanges with designers. Our analysis shows that these tools do not merely execute instructions but interpret, propose, and adapt design outputs in response to evolving human input. However, while this suggests a shift toward shared authorship, existing frameworks lack a clear model for managing such co-agency in real-world workflows. Thus, future research should build collaborative frameworks that formalize how prompts, feedback loops, and system-generated alternatives function as joint acts of design reasoning. These frameworks should map the interdependencies between human intent and machine proposal, clarifying how each party contributes to and negotiates the evolving artifact.

#### 5.3.2. Changing How We Design: Understanding the Impact of GenUI on User Interface Design Practice

Our literture review identifies representation fidelity, temporal context, and adaptivity/plasticity as dimensions through which GenUI transforms traditional design practices. GenUI enables seamless transitions between text, image, code, and layout at design time, facilitating real-time synthesis rather than post hoc adaptation. This affordance dramatically expands the exploratory potential of interface design but also risks displacing critical evaluation with rapid iteration. Future work must investigate how these capabilities affect both the quality and originality of design outcomes over time. For instance, does multimodal translation encourage broader ideation or reinforce superficial convergence on familiar patterns? How do designers use—or misuse—adaptive generation during high-stakes decision-making? By examining how GenUI tools affect representation choices, iteration rhythms, and solution diversity, future research can assess the creative and procedural impacts of generative assistance across settings.

#### 5.3.3. Building Trustworthy Tools: Addressing Ethical and Responsible Use of GenUIs

The feedback/explorability, design responsibility, and system agency dimensions in our findings point to critical ethical and epistemological challenges. While GenUI systems afford rapid feedback and ideation through dialogic interaction, they often mask the underlying generative logic or rationale behind their creations. Designers may struggle to understand why certain suggestions were made, whether outputs are contextually appropriate, or how the input influences generative outomces. This creates a gap between surface usability and deep accountability. Moreover, the shifting locus of authorship—where systems contribute substantively to the interface’s structure—raises unresolved questions about intellectual ownership, accountability for biased outputs, and user agency. Future work must embed mechanisms for transparency, contestability, and reconfigurability into GenUI workflows. This includes features such as provenance tracking, ethical auditing of training data, and value-aligned prompt structures to ensure that generative tools serve diverse and inclusive design values, not just efficiency or novelty.

## 6\. Conclusion

This paper introduced a working definition of designing Generative User Interfaces (GenUI), clarifying key characteristics that set GenUI apart from traditional UI development and other forms of generative design. Through a systematic literature review, expert interviews, and case studies, we identified five foundational themes. These themes frame GenUI as an interactive, socio-technical design process, where human designers and AI systems iteratively co-construct interface artifacts. The definition offers a shared vocabulary and conceptual grounding for analyzing and designing generative systems in UI contexts. Beyond conceptual clarification, this work provides practical insights for understanding GenUI in terms of design outcomes as well as design process, emphasizing hybrid creation workflows, curation-based roles, and iterative refinement strategies.

While this study offers a foundational perspective, several limitations must be noted. The empirical base—though rich in qualitative insights—draws primarily from early adoption contexts and professional design environments, potentially limiting generalizability to non-professional or cross-domain settings. Our expert sample, while diverse, may skew toward frontier tool adopters, underrepresenting conventional practices. Additionally, the interpretive nature of our thematic synthesis involves subjective judgment, particularly in delineating evolving constructs like “co-creation.” Future work should complement these findings with longitudinal studies, experimental evaluations, and participatory methods to validate and extend the framework proposed here.

Looking ahead, several research directions remain critical. First, new evaluation frameworks are needed to assess GenUI outputs beyond usability, incorporating novelty, contextual fit, transparency, and ethical alignment. Second, optimal models of human–AI interaction require exploration: How should systems visualize intermediate states, and how can feedback mechanisms best support interpretability? Third, GenUI is reshaping design cognition, necessitating studies on how generative tools influence problem-solving and learning. Fourth, maintaining user-centeredness remains a challenge, as generative systems risk prioritizing visual output over real user needs. Finally, generative capabilities may enable novel methodologies such as adaptive prototyping, dynamic personalization, and continuous interface evolution—rich areas for future inquiry. As generative technologies continue to evolve, so must the framework, which adapts to emerging modalities, capabilities, and user values in a more responsible manner.

###### Acknowledgements.

I am grateful to my collaborators, such as Dr. Dajung Kim, Seoyeong Hwang and Haeeun Shin, for their thoughtful feedback, critical insights, and generous engagement throughout this work. Their perspectives enriched the depth and direction of the research, particularly in clarifying the framework and polishing the findings. This research was partially supported by a grant from the Korea Institute for Advancement of Technology (KIAT) funded by the Government of Korea (MOTIE) (P0025495, Establishment of Infrastructure for Integrated Utilization of Design Industry Data). This work was also partially supported by the Technology Innovation Program (20015056, Commercialization design and development of Intelligent Product-Service System for personalized full silver life cycle care) funded by the Ministry of Trade, Industry & Energy(MOTIE, Korea).

[^2]: Claude AI. 2025. New Claude AI. [https://claude.ai/new](https://claude.ai/new) Accessed: 2025-03-22.

[^3]: Bashar Altakrouri and Andreas Schrader. 2012. Towards dynamic natural interaction ensembles. In *the 26th BCS Conference on Human Computer Interaction*. BCS Learning & Development. [https://www.scienceopen.com/hosted-document?doi=10.14236/ewic/HCI2012.85](https://www.scienceopen.com/hosted-document?doi=10.14236/ewic/HCI2012.85)

[^4]: Victor Alvarez-Cortes, Benjamin E Zayas-Perez, Victor Huga Zarate-Silva, and Jorge A Ramirez Uresti. 2007. Current trends in adaptive user interfaces: Challenges and applications. In *Electronics, Robotics and Automotive Mechanics Conference (CERMA 2007)*. IEEE, 312–317.

[^5]: Nancy S. Anderson. 1988. User centered system design: new perspectives on human-computer interaction. [https://www.jstor.org/stable/1422802](https://www.jstor.org/stable/1422802)

[^6]: Maria Becker, Siting Liang, and Anette Frank. 2021. Reconstructing implicit knowledge with language models. In *Proceedings of Deep Learning Inside Out (DeeLIO): The 2nd Workshop on Knowledge Extraction and Integration for Deep Learning Architectures*. 11–24. [https://aclanthology.org/2021.deelio-1.2/](https://aclanthology.org/2021.deelio-1.2/)

[^7]: Adream Blair-Early and Mike Zender. 2008. User interface design principles for interaction design. *Design Issues* 24, 3 (2008), 85–107. [https://www.jstor.org/stable/25224185](https://www.jstor.org/stable/25224185) Publisher: JSTOR.

[^8]: Kristopher J. Blom and Steffi Beckhaus. 2014. The design space of dynamic interactive virtual environments. *Virtual Reality* 18, 2 (June 2014), 101–116. [doi:10.1007/s10055-013-0232-y](https://doi.org/10.1007/s10055-013-0232-y)

[^9]: Margaret A. Boden. 2004. *The creative mind: Myths and mechanisms*. Routledge.

[^10]: Bolt. 2025. Bolt New. [https://bolt.new/](https://bolt.new/) Accessed: 2025-03-22.

[^11]: Neill D. F. Campbell and Jan Kautz. 2014. Learning a manifold of fonts. *ACM Transactions on Graphics* 33, 4 (July 2014), 1–11. [doi:10.1145/2601097.2601212](https://doi.org/10.1145/2601097.2601212)

[^12]: John M. Carroll, Robert L. Mack, and Wendy A. Kellogg. 1988a. Interface metaphors and user interface design. In *Handbook of human-computer interaction*. Elsevier, 67–85. [https://www.sciencedirect.com/science/article/pii/B9780444705365500087](https://www.sciencedirect.com/science/article/pii/B9780444705365500087)

[^13]: John M Carroll, Robert L Mack, and Wendy A Kellogg. 1988b. Interface metaphors and user interface design. In *Handbook of human-computer interaction*. Elsevier, 67–85.

[^14]: Mark Chen, Alec Radford, Rewon Child, Jeffrey Wu, Heewoo Jun, David Luan, and Ilya Sutskever. 2020. Generative pretraining from pixels. In *International conference on machine learning*. PMLR, 1691–1703. [http://proceedings.mlr.press/v119/chen20s.html](http://proceedings.mlr.press/v119/chen20s.html)

[^15]: Zhiqin Chen and Hao Zhang. 2019. Learning implicit fields for generative shape modeling. In *Proceedings of the IEEE/CVF conference on computer vision and pattern recognition*. 5939–5948.

[^16]: Simon Colton. 2008. Creativity Versus the Perception of Creativity in Computational Systems.. In *AAAI spring symposium: creative intelligent systems*, Vol. 8. Palo Alto, CA, 7.

[^17]: Nigel Cross. 1982. Designerly ways of knowing. *Design studies* 3, 4 (1982), 221–227. [https://www.sciencedirect.com/science/article/pii/0142694X82900400](https://www.sciencedirect.com/science/article/pii/0142694X82900400) Publisher: Elsevier.

[^18]: Cursor. 2025. Cursor AI. [https://www.cursor.com/](https://www.cursor.com/) Accessed: 2025-03-22.

[^19]: Alan Dix. 2010. Human–computer interaction: A stable discipline, a nascent science, and the growth of the long tail. *Interacting with computers* 22, 1 (2010), 13–27.

[^20]: Kees Dorst. 2011. The core of ‘design thinking’and its application. *Design studies* 32, 6 (2011), 521–532. [https://www.sciencedirect.com/science/article/pii/S0142694X11000603](https://www.sciencedirect.com/science/article/pii/S0142694X11000603) Publisher: Elsevier.

[^21]: Gerhard Fischer, Elisa Giaccardi, Yunwen Ye, Alistair G Sutcliffe, and Nikolay Mehandjiev. 2004. Meta-design: a manifesto for end-user development. *Commun. ACM* 47, 9 (2004), 33–37.

[^22]: Thomas Fischer and Christiane M. Herr. 2001. Teaching generative design. In *Proceedings of the 4th Conference on Generative Art*. Politechnico di Milano University Milan, 8. [http://www.generativeart.com/on/cic/ga2001\_pdf/fischer.pdf](http://www.generativeart.com/on/cic/ga2001_pdf/fischer.pdf)

[^23]: Susan Gasson. 2003. Human-centered vs. user-centered approaches to information system design. *Journal of Information Technology Theory and Application (JITTA)* 5, 2 (2003), 5. [https://aisel.aisnet.org/cgi/viewcontent.cgi?article=1153&context=jitta](https://aisel.aisnet.org/cgi/viewcontent.cgi?article=1153&context=jitta)

[^24]: John S. Gero and Udo Kannengiesser. 2004. The situated function–behaviour–structure framework. *Design studies* 25, 4 (2004), 373–391. [https://www.sciencedirect.com/science/article/pii/S0142694X03000735](https://www.sciencedirect.com/science/article/pii/S0142694X03000735) Publisher: Elsevier.

[^25]: GitHub. 2025. GitHub Copilot. [https://github.com/features/copilot](https://github.com/features/copilot) Accessed: 2025-03-22.

[^26]: Ian J. Goodfellow, Jean Pouget-Abadie, Mehdi Mirza, Bing Xu, David Warde-Farley, Sherjil Ozair, Aaron Courville, and Yoshua Bengio. 2014. Generative adversarial nets. *Advances in neural information processing systems* 27 (2014). [https://proceedings.neurips.cc/paper\_files/paper/2014/hash/f033ed80deb0234979a61f95710dbe25-Abstract.html](https://proceedings.neurips.cc/paper_files/paper/2014/hash/f033ed80deb0234979a61f95710dbe25-Abstract.html)

[^27]: Eric Horvitz. 1999. Principles of mixed-initiative user interfaces. In *Proceedings of the SIGCHI conference on Human Factors in Computing Systems*. 159–166.

[^28]: Adobe Inc. 2025. Adobe Creative Cloud. [https://www.adobe.com/creativecloud.html](https://www.adobe.com/creativecloud.html) Accessed: 2025-03-22.

[^29]: Nanna Inie and Peter Dalsgaard. 2020. How Interaction Designers Use Tools to Manage Ideas. *ACM Transactions on Computer-Human Interaction* 27, 2 (April 2020), 1–26. [doi:10.1145/3365104](https://doi.org/10.1145/3365104)

[^30]: Anthony Jameson. 2007. Adaptive interfaces and agents. In *The human-computer interaction handbook*. CRC press, 459–484.

[^31]: Bernard J Jansen. 1998. The graphical user interface. *ACM SIGCHI Bulletin* 30, 2 (1998), 22–26.

[^32]: Tae-seok Kim, Marvin John Ignacio, Seounghee Yu, Hulin Jin, and Yong-guk Kim. 2024. UI/UX for Generative AI: Taxonomy, Trend, and Challenge. *IEEE Access* (2024).

[^33]: N. Kita and K. Miyata. 2016. Aesthetic Rating and Color Suggestion for Color Palettes. *Computer Graphics Forum* 35, 7 (Oct. 2016), 127–136. [doi:10.1111/cgf.13010](https://doi.org/10.1111/cgf.13010)

[^34]: Sivam Krish. 2011. A practical generative design method. *Computer-aided design* 43, 1 (2011), 88–100. [https://www.sciencedirect.com/science/article/pii/S0010448510001764](https://www.sciencedirect.com/science/article/pii/S0010448510001764) Publisher: Elsevier.

[^35]: Justin Matejka, Michael Glueck, Erin Bradner, Ali Hashemi, Tovi Grossman, and George Fitzmaurice. 2018. Dream Lens: Exploration and Visualization of Large-Scale Generative Design Datasets. In *Proceedings of the 2018 CHI Conference on Human Factors in Computing Systems*. ACM, Montreal QC Canada, 1–12. [doi:10.1145/3173574.3173943](https://doi.org/10.1145/3173574.3173943)

[^36]: David Moher, Alessandro Liberati, Jennifer Tetzlaff, Douglas G Altman, Prisma Group, et al. 2010. Preferred reporting items for systematic reviews and meta-analyses: the PRISMA statement. *International journal of surgery* 8, 5 (2010), 336–341.

[^37]: Michael J. Muller and Sarah Kuhn. 1993. Participatory design. *Commun. ACM* 36, 6 (June 1993), 24–28. [doi:10.1145/153571.255960](https://doi.org/10.1145/153571.255960)

[^38]: Brad A Myers. 1998. A brief history of human-computer interaction technology. *interactions* 5, 2 (1998), 44–54.

[^39]: Brad A Myers. 2001. Using handhelds and PCs together. *Commun. ACM* 44, 11 (2001), 34–41.

[^40]: Jakob Nielsen. 1994. *Usability engineering*. Morgan Kaufmann.

[^41]: Donald A Norman. 1986. Cognitive engineering. *User centered system design* 31, 61 (1986), 2.

[^42]: Peter O’Donovan, Aseem Agarwala, and Aaron Hertzmann. 2015. DesignScape: Design with Interactive Layout Suggestions. In *Proceedings of the 33rd Annual ACM Conference on Human Factors in Computing Systems*. ACM, Seoul Republic of Korea, 1221–1224. [doi:10.1145/2702123.2702149](https://doi.org/10.1145/2702123.2702149)

[^43]: OpenAI. 2025. Hello GPT-4o. [https://openai.com/index/hello-gpt-4o/](https://openai.com/index/hello-gpt-4o/) Accessed: 2025-03-22.

[^44]: Rivka Oxman. 2006. Theory and design in the first digital age. *Design studies* 27, 3 (2006), 229–265. [https://www.sciencedirect.com/science/article/pii/S0142694X05000840](https://www.sciencedirect.com/science/article/pii/S0142694X05000840) Publisher: Elsevier.

[^45]: Aditya Ramesh, Mikhail Pavlov, Gabriel Goh, Scott Gray, Chelsea Voss, Alec Radford, Mark Chen, and Ilya Sutskever. 2021. Zero-shot text-to-image generation. In *International conference on machine learning*. Pmlr, 8821–8831. [https://proceedings.mlr.press/v139/ramesh21a.html?ref=journey](https://proceedings.mlr.press/v139/ramesh21a.html?ref=journey)

[^46]: Partha Pratim Ray. 2025. A Review on Vibe Coding: Fundamentals, State-of-the-art, Challenges and Future Directions. (2025).

[^47]: Donald A. Schön. 2017. *The reflective practitioner: How professionals think in action*. Routledge. [https://www.taylorfrancis.com/books/mono/10.4324/9781315237473/reflective-practitioner-donald-sch%C3%B6n](https://www.taylorfrancis.com/books/mono/10.4324/9781315237473/reflective-practitioner-donald-sch%C3%B6n)

[^48]: Ben Shneiderman. 1983. Direct manipulation: A step beyond programming languages. *Computer* 16, 08 (1983), 57–69.

[^49]: Ben Shneiderman. 2003. The eyes have it: A task by data type taxonomy for information visualizations. In *The craft of information visualization*. Elsevier, 364–371.

[^50]: Debbie Stone, Caroline Jarrett, Mark Woodroffe, and Shailey Minocha. 2005. *User interface design and evaluation*. Elsevier. [https://books.google.com/books?hl=en&lr=&id=VvSoyqPBPbMC&oi=fnd&pg=PR21&dq=user+interface+design&ots=d9MWTXlLO8&sig=5g0t7oP5jDTGRi8zvspvF8IiotQ](https://books.google.com/books?hl=en&lr=&id=VvSoyqPBPbMC&oi=fnd&pg=PR21&dq=user+interface+design&ots=d9MWTXlLO8&sig=5g0t7oP5jDTGRi8zvspvF8IiotQ)

[^51]: David Thevenin and Joëlle Coutaz. 1999. Plasticity of user interfaces: Framework and research agenda.. In *Interact*, Vol. 99. Citeseer, 110–117.

[^52]: Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit, Llion Jones, Aidan N. Gomez, Łukasz Kaiser, and Illia Polosukhin. 2017. Attention is all you need. *Advances in neural information processing systems* 30 (2017). [https://proceedings.neurips.cc/paper/2017/hash/3f5ee243547dee91fbd053c1c4a845aa-Abstract.html](https://proceedings.neurips.cc/paper/2017/hash/3f5ee243547dee91fbd053c1c4a845aa-Abstract.html)

[^53]: John Whiteside, John Bennett, and Karen Holtzblatt. 1988. Usability engineering: Our experience and evolution. In *Handbook of human-computer interaction*. Elsevier, 791–817.

[^54]: Qian Yang, Aaron Steinfeld, Carolyn Rosé, and John Zimmerman. 2020. Re-examining Whether, Why, and How Human-AI Interaction Is Uniquely Difficult to Design. In *Proceedings of the 2020 CHI Conference on Human Factors in Computing Systems*. ACM, Honolulu HI USA, 1–13. [doi:10.1145/3313831.3376301](https://doi.org/10.1145/3313831.3376301)

[^55]: Qian Yang, Aaron Steinfeld, and John Zimmerman. 2019. Unremarkable AI: Fitting Intelligent Decision Support into Critical, Clinical Decision-Making Processes. In *Proceedings of the 2019 CHI Conference on Human Factors in Computing Systems*. ACM, Glasgow Scotland Uk, 1–11. [doi:10.1145/3290605.3300468](https://doi.org/10.1145/3290605.3300468)

[^56]: Haiyi Zhu, Bowen Yu, Aaron Halfaker, and Loren Terveen. 2018. Value-Sensitive Algorithm Design: Method, Case Study, and Lessons. *Proceedings of the ACM on Human-Computer Interaction* 2, CSCW (Nov. 2018), 1–23. [doi:10.1145/3274463](https://doi.org/10.1145/3274463)